feat: 동아리관련 api 구현
i-am-here-too/iht-backend pull request #20
Opened 2024-02-23 08:39 UTC by kong-hana01

### 관련 이슈
resolved: #17 

### 노트
- 이슈 내 api 구현
- 테스트 코드 작성
  - 서비스는 bdd 형식 테스트
  - 컨트롤러는 restAssured에 기반한 통합 테스트 진행(Dirties Context 사용으로 인한 성능 저하 이슈 o)
  - 추후 커스텀 예외를 따로 관리하는 advice 객체 구현 이후 테스트 코드 변경 예정
- 현재 인가관련 처리가 되어있지 않음

2024-02-26 14:36 UTC, echo724 requested changes
수고하셨습니다! 그 예외 빠진 부분만 구현해서 넣으면 될꺼같아요! 역시,, 콩코드 ,, 여객기처럼 깔끔하네요

2024-02-26 14:36 UTC, echo724 commented on src/test/kotlin/com/haru/attendance/controller/ClubControllerTest.kt
> +        Given {
저도 이런방식으로 테스트하려고 했는데 딱 맞았군요!

2024-02-26 14:36 UTC, echo724 commented on src/main/kotlin/com/haru/attendance/service/ClubService.kt
> +            .validateAndGet()
오홍 이런 방식으로 검증을 해서 가져오는군요?! 좋은거 같습니다!

2024-02-26 14:36 UTC, echo724 commented on src/test/kotlin/com/haru/attendance/controller/ClubControllerTest.kt
> +            // TODO: 커스텀 예외 처리 구현
이 부분은 구현이 아직 안된건가요?! ClubNotFound 이런 계통의 예외일꺼 같아서요!

2024-02-26 14:36 UTC, echo724 commented on src/test/kotlin/com/haru/attendance/controller/ClubControllerTest.kt
> +            // TODO: 커스텀 예외 처리 구현
앗 이부분도요!

2024-02-26 14:36 UTC, echo724 commented on src/test/kotlin/com/haru/attendance/service/ClubServiceTest.kt
> +        val clubName = "나이트 클럽"
헉..😦

2024-02-27 07:31 UTC, echo724 commented on src/main/kotlin/com/haru/attendance/controller/ClubController.kt
> +        return ResponseEntity.status(HttpStatus.CREATED).body(clubService.save(clubSaveRequest))
이부분 Created와 함께 Location Header를 추가해주는건 어떨까요?! 아직 프론트랑 얘기가 안된 부분이긴 한데, created와 함께 location url을 같이 넣어준다고 하네요?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201

2024-02-27 07:46 UTC, echo724 commented on src/main/kotlin/com/haru/attendance/controller/ClubController.kt
> +@Controller
차이는 별로 없을 수 있는데 @RestController로 명시하면 좋을꺼 같아요!

2024-02-28 08:36 UTC, kong-hana01 commented on src/test/kotlin/com/haru/attendance/controller/ClubControllerTest.kt
> +            // TODO: 커스텀 예외 처리 구현
Controller 테스트의 결과여서 그렇습니다! 
지금 `커스텀 예외에 대해 서버에서 따로 처리를 해주고 있지 않아서 예외가 발생하면 모두 500 error가 반환`돼요!
이 부분은 해당 pr이 반영된 이후에 ControllerAdvice를 만들어서 커스텀 예외를 따로 처리하고 응답하면 좋을 것 같아요 ㅎㅎ

2024-02-28 08:38 UTC, kong-hana01 commented on src/main/kotlin/com/haru/attendance/controller/ClubController.kt
> +        return ResponseEntity.status(HttpStatus.CREATED).body(clubService.save(clubSaveRequest))
> 아직 프론트랑 얘기가 안된 부분이긴 한데, created와 함께 location url을 같이 넣어준다고 하네요?

마자용!
만약 location이 들어가게 된다면 `/club/1` 이런 식의 주소가 들어가는 거겠죠?
이건 회의 때 한번 이야기해보시죠!

2024-02-28 08:55 UTC, kong-hana01 commented on src/main/kotlin/com/haru/attendance/controller/ClubController.kt
> +@Controller
좋은 의견이네요! ㅎㅎ

이 부분에 대해 에코와 이야기하고 싶은 부분이 하나 있습니다!
@RestController는 `@Controller + @ResponseBody가 포함되어서` 핸들러에서 객체를 직접 반환할 때 json으로 반환하도록 돕는 역할을 하는 것으로 알고 있어요!
`ResponseEntity<>`를 사용한다면 ResponseBody를 사용하지 않아도 json으로 반환되어서 @Controller만 사용해도 괜찮고요!

만약 어떤 핸들러에서 `객체를 반환한다면 @RestController를 사용`하고, 
`ResponseEntity<>를 반환한다면 @Controller를 사용`하는 게 좋아보이는데 에코의 의견은 어떠신가요?

2024-02-29 08:46 UTC, echo724 commented on src/main/kotlin/com/haru/attendance/controller/ClubController.kt
> +@Controller
저는 전자가 낫다고 생각합니다! 백엔드 서버이기 때문에 REST임을 명시적으로 보여주는 장점도 있고 ResponseEntity를 따로 붙이지 않아서 좋을꺼 같아요!

2024-02-29 08:46 UTC, echo724 commented on src/main/kotlin/com/haru/attendance/controller/ClubController.kt
> +        return ResponseEntity.status(HttpStatus.CREATED).body(clubService.save(clubSaveRequest))
네넵 맞숩니다~!

2024-02-29 08:46 UTC, echo724 commented on src/test/kotlin/com/haru/attendance/controller/ClubControllerTest.kt
> +            // TODO: 커스텀 예외 처리 구현
아항 그렇군요! 네네 합치면서 같이 작업해두죠~!

2024-03-01 04:10 UTC, echo724 approved these changes

2024-03-04 07:14 UTC, merged